my_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ip94038.us-east4.gcp
      user: jacksongeorgetown
      password: *************
      database: RAW
      schema: POKEMON
